[project]
name = "lecture-env"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]  # Add "win-64" if you need Windows support

[dependencies]
python = "3.9.*"
numpy = "*"
scipy = "*"
matplotlib = "*"
jupyter = "*"
notebook = "6.*"
pandas = "*"
scikit-learn = "*"
scikit-image = "*"
uncertainties = "*"
opencv = "*"
pandoc = "*"
jupyter-book = "*"
sphinx  = "*"
myst-parser  = "*"
pydata-sphinx-theme = "*"
ipywidgets = "*"
astropy = "*"
dask = "*"
dask-image = "*"
mysqlclient = "*"  # assuming you meant MySQL client bindings for Python
seaborn = "*"
tifffile = "*"
tqdm = "*"
pytest = "*"
matplotlib-scalebar = "*"
ffmpeg = "*"
jupyter_contrib_nbextensions = "*"
rise = "*"
bokeh = "*"
pyvista = "*"
python-graphviz = "*"
pydot = "*"
trame = "*"
trame-vtk = "*"
trame-vuetify = "*"
vtk = "*"
ipyvtklink = "*"
ipygany = "*"
pythreejs = "*"
meshio = "*"
netcdf4 = "*"
h5py = "*"
pillow = "*"
pip = "*"
plotly = "5.*"
ipyvolume = "*"
ipyvuetify = "*"
shapely = "*"
SimpleITK = "*"