# Book settings
title: Quantitative Big Imaging - Complex shapes
only_build_toc_files: true

author: Anders Kaestner
language: en
logo: figures/07-all_icons-advancedshapes.png

execute:
  timeout: -1
  execute_notebooks: auto

latex:
  latex_documents:
     targetname: QBI-Lecture07-ComplexShape.tex
