# Book settings
title: Quantitative Big Imaging - Image enhancement
only_build_toc_files: true

author: Anders Kaestner
language: en
#logo: 'images/logo.png'


execute:
  timeout: -1
  execute_notebooks: auto

latex:
  latex_documents:
     targetname: QBI-Lecture03-ImageEnhancement.tex
